# Generated by Django 5.2.8 on 2025-11-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="idx_company_name"),
                    models.Index(fields=["created_at"], name="idx_company_created"),
                ],
            },
        ),
    ]
